# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Stevens Cypress 
email: michael.greenberg@stevens.edu
organizer: Michael Greenberg
description: >- # this means to ignore newlines until "baseurl:"
  The Cypress group at Stevens Institute of Technology studies cybersecurity, programming languages, and systems.
meeting_time: "Wednesdays at 12pm-1pm"
meeting_location: "Gateway South 222"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# build settings
plugins:
  - jekyll-feed    # for RSS
  - jekyll-seo-tag # for nice headers on Twitter, etc.

# set up 
defaults:
  - scope:
      path: ""      # all files
      type: posts   # limit to posts
    values:
      type: "post" 
  - scope:
      path: ""      # all files
      type: pages   # limit to pages
    values:
      type: "page"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
